<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PensaComigo.Application\PensaComigo.Application.csproj" />
    <ProjectReference Include="..\PensaComigo.Domain\PensaComigo.Domain.csproj" />
  </ItemGroup>

</Project>
